#!/bin/bash

default_hexo_home=~/hexo

depends=(
	# hexo 的基本组件
	# 	https://github.com/hexojs/hexo-starter/blob/master/package.json#L14
	hexo
	hexo-generator-archive
	hexo-generator-category
	hexo-generator-index
	hexo-generator-tag
	hexo-renderer-ejs
	hexo-renderer-stylus
	hexo-server

	# 其它 markdown 渲染支持（如 emoji）
	# 	https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus#install
	hexo-renderer-markdown-it-plus

	# git 一键部署支持
	# 	https://hexo.io/zh-cn/docs/one-command-deployment#Git
	hexo-deployer-git
)

cnpm(){
	# https://developer.aliyun.com/mirror/NPM
	npm --registry=https://registry.npm.taobao.org \
		--cache=$HOME/.npm/.cache/cnpm \
		--disturl=https://npm.taobao.org/dist \
		--userconfig=$HOME/.cnpmrc "$@"
}

main(){
	# 安装 hexo 所需的依赖
	# $1 指定hexo 目录，若不指定，则为默认值
	[ "$hexo_home" ] || hexo_home="$default_hexo_home"

	cd "$hexo_home" || exit 1
	cnpm install ${depends[*]} --save || exit 1
}

main

