#!/bin/bash

workdir="$(cd "$(dirname "$0")" && pwd)"

default_hexo_home=~/hexo

main(){
	# $1 指定博客主目录，若不指定，则为默认值
	
	local hexo_home="$1"
	
	[ "$hexo_home" ] || hexo_home="$default_hexo_home"
	
	# 修补已存在的主题目录
	for theme in $(ls "$hexo_home/themes"); do
		if [ -d "$workdir/themes/$theme" ]; then
			cp -sfr "$workdir/themes/$theme/"* "$hexo_home/themes/$theme/" || exit 1
		fi
	done
	
	# 修补 node_modules 目录
	cp -sfr "$workdir/node_modules" "$hexo_home" || exit 1
	
	# 确保所设置的主题存在，若不存在则自动选个已存在的主题
	cur_theme="$(cat "$workdir/_config.yml" | grep '^theme:' | cut -c8-)"
	if [ ! -d "$hexo_home/themes/$cur_theme" ]; then
		# 寻找有效主题
		for theme in $(ls "$hexo_home/themes"); do
			[ -d "$hexo_home/themes/$theme" ] || continue
			cur_theme="$theme"
			break
		done
		if [ ! -d "$hexo_home/themes/$cur_theme" ]; then
			echo "在 $hexo_home/themes 中找不到有效主题！" >&2
			exit 1
		fi
		
		# 修改 _config.yml 的主题为有效主题
		sed -i 's/^theme: .*/theme: '"$cur_theme"'/g' "$workdir/_config.yml"
	fi
}

main "$@"


