#!/bin/bash

workdir="$(cd "$(dirname "$0")" && pwd)"

default_hexo_home=~/hexo

main(){
	# $1 指定博客主目录，若不指定，则为默认值
	
	local hexo_home="$1"
	
	[ "$hexo_home" ] || hexo_home="$default_hexo_home"
	
	hexo deploy --cwd "$hexo_home" || exit 1
}

main "$@"


