#!/bin/bash

workdir="$(cd "$(dirname "$0")" && pwd)"

default_hexo_home=~/hexo

main(){
	# 将博客发布
	# $1 指定hexo 目录，若不指定，则为默认值
	[ "$hexo_home" ] || hexo_home="$default_hexo_home"

	# 将博客发布
	cd "$hexo_home"
	npx hexo clean && \
		npx hexo generate && \
		npx hexo deploy
}

main
