#!/bin/bash

workdir="$(cd "$(dirname "$0")" && pwd)"

default_hexo_home=~/hexo
default_public_branch=~/e.coding.net/fkxxyz

main(){
	# $1 指定hexo 目录，若不指定，则为默认值
	# $2 指定网站的本地仓库目录，若不指定，则为默认值

	local hexo_home="$1"
	local public_branch="$2"
	[ "$hexo_home" ] || hexo_home="$default_hexo_home"
	[ "$public_branch" ] || public_branch="$default_public_branch"
	
	# 若目标已存在，则要确保当前存在的是已经链接过的博客目录，再删除
	if [ -d "$hexo_home" ]; then
		if [ ! -h "$hexo_home/source" ]; then
			echo "目标目录 $hexo_home 无法识别！请确保此目录无用，手动删除后重试。" >&2
			exit 1
		fi
		rm -rf "$hexo_home" || exit 1
	fi

	echo "开始构建 hexo 目录..."
	mkdir "$hexo_home"
	cd "$hexo_home"
	"$workdir/install_depends" "$hexo_home"

	echo "修补 hexo 目录..."
	ln -s "$workdir/_config.yml" "$hexo_home/_config.yml" || exit 1
	ln -s "$workdir/source" "$hexo_home/source" || exit 1
	ln -s "$public_branch" "$hexo_home/.deploy_git" || exit 1
	ln -s "$workdir/package.json" "$hexo_home/package.json" || exit 1

	# 获取所用的主题
	theme_name="$(sed -n 's/^theme: \+\([[:alnum:]_]\+\)/\1/p' _config.yml)" || exit 1

	echo "开始构建主题目录..."
	theme_dir="$hexo_home/themes/$theme_name"
	mkdir -p "$hexo_home/themes" || exit 1
	mkdir "$theme_dir" || exit 1
	cd "$theme_dir" || exit 1
	"$workdir/themes/$theme_name/.install_depends" "$hexo_home" || exit 1

	echo "修补主题目录..."
	ln -sf "$workdir/themes/$theme_name/"* "$theme_dir" || exit 1
}

main "$@"
