menu:
  主页: /
  分类: /categories
  归档: /archives
  标签: /tags
  关于: /about

sidebar: right

widgets:
- search
- category
- recent_posts
- tag
- tagcloud

# Duoshuo
duoshuo_shortname: 

fancybox: true

google_analytics:
rss: 
google_site_verification: 
baidu_site_verification: 
icon: 
